baseURL: "http://carlosr.me/"
title: Carlos Ramos
paginate: 8
theme:
  - dark
  - hugo-shortcode-gallery
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    weight: 1
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Blog
          url: series/blog
          weight: 5
        - name: Projects
          url: series/projects
          weight: 10
        # - name: Categories
        #   url: categories
        #   weight: 10
        # - name: Search
        #   url: search
        #   weight: 10
        - name: About
          url: about
          weight: 20
        # - name: Series
        #   url: series
        #   weight: 20

#   l2:
#     languageName: "Lang2"
#     weight: 2
#     title: PaperModL2
#     profileMode:
#       enabled: true
#       title: PaperMod
#       # imageUrl: "#"
#       # imageTitle: my image
#       # imageWidth: 120
#       # imageHeight: 120
#       subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ðŸŒ™ Smooth | ðŸ“± Responsive"
#       buttons:
#         - name: Blog
#           url: posts
#         - name: Tags
#           url: tags
#     menu:
#       main:
#         - name: Archive
#           url: archives/
#           weight: 5
#         - name: Tags
#           url: tags
#           weight: 10
#         - name: Categories
#           url: categories
#           weight: 10
#         - name: Series
#           url: series
#           weight: 10
#         - name: NullLink
#           url: "#"
#         - name: NullLink2
#           url: "#"
#         - name: NullLink3
#           url: "#"

#   l3:
#     languageName: "Langrtl"
#     languagedirection: rtl
#     weight: 3
#     title: PaperMod RTL
#     homeInfoParams:
#       Title: "Hi there \U0001F44B"
#       Content: Welcome to RTL layout
#     menu:
#       main:
#         - name: Tags
#           url: tags
#           weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: development
  description: "jc - https://github.com/adityatelange/hugo-PaperMod"
  author: jc
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: false
  mainSections: ["projects", "posts"]
  defaultTheme: auto
  ShowShareButtons: false
  # disableThemeToggle: true
  displayFullLangName: true
  # images: ""
  assets:
    favicon: "/site/favicon.ico"
    favicon16x16:  "/site/favicon-16x16.png"
    favicon32x32:  "/site/favicon-32x32.png"
    apple_touch_icon:  "/site/apple-touch-icon.png"

  profileMode:
    enabled: false
    title: Carlos Ramos
    subtitle: >
      I am a MSc. student in the Data Systems group at the University of Tartu. I received a BSc in Computer Science, and previously worked on networked systems, cloud applications, and visualization.
      I am  interested in distributed and data systems, visualization, sound synthesis, and education. I want to help people by providing better tools for learning and building.

    imageUrl: "/profile.jpg"
    imageTitle: profile
    imageWidth: 128
    imageHeight: 128
    # buttons:
    #   - name: ResumÃ©
    #     url: archives

  # homeInfoParams:
  #   Title: "Hi there"
  #   Content: >
  #     Welcome to demo of hugo's jc.

  #     - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

  socialIcons:
    - name: github
      url: "https://github.com/0x7b1"
    - name: twitter
      url: "http://twitter.com/_0x7b1"
    - name: cv
      url: "/docs/cv.pdf"

markup:
  highlight:
    codeFences: true
    style: swapoff
    # lineNos: true

taxonomies:
  # category: categories
  tag: tags
  series: series

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

# services:
#   instagram:
#     disableInlineCSS: true
#   twitter:
#     disableInlineCSS: true
